import requests
import base64
import json

URL = "https://semaphore.deway.fr/auth/logout"

headers = {
    "Accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InpRUGFKelJGSGVjOTNhcWVtSndxVGlsbF9CZFNhd0tJZW8waWx0SGdJMW8iLCJ0eXAiOiJKV1QifQ.eyJ1c2VyX2lkIjoiMjIyMjIyMjItMjIyMi0yMjIyLTIyMjItMjIyMjIyMjIyMjIxIiwidXNlcl90eXBlIjoiYWRtaW4iLCJzY2hvb2xfaWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJhZG1pbl9yb2xlIjoic3VwZXJfYWRtaW4iLCJpc3MiOiJzZW1hcGhvcmUtYXV0aC1pZGVudGl0eSIsInN1YiI6IjIyMjIyMjIyLTIyMjItMjIyMi0yMjIyLTIyMjIyMjIyMjIyMSIsImV4cCI6MTc2OTc3MjkxOSwiaWF0IjoxNzY5NzcyMDE5fQ.ZDgq-E0gjXpVpfjpGp_nI4Vv9wamfWq8WeqKYChYXP48tJEMDP9GZSLNKG_8YdeePAM003nnHKBIeY36LYgTcQ_87jKdmH3mpXDVaMixIWqPxeqvf9ba5kNGcVymBBfOEHplUfqOaoFCLsbEZeKosC8TJyIwLZzSwBhRefC3xSBiGPbZEdK27r6lGimjW_-g6ESeFa10CIfB8tsn005JTjjilUYa-PVYii0h8EJEdlsyv1ELcVXdb5pSyjuL1c_QrHURlPWgaWRu6oBFwLQk6bnLBGSfnK1E1Ehagl2SvlGhMOaI-AD7AZi8U5QhZmk0SQxe4LGZ_MlaUOJ3ukqUnw"
}

response = requests.post(URL, headers=headers)

# Vérification
response.raise_for_status()

data = response.json()
print(data)
